name: Build & Deploy tracking-events

on:
  push:
    branches: [main]
    paths:
      - routebox-tracking-events/**
      - k8s/tracking-events/**

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 957424402576.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: routebox-dev/tracking-events

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::957424402576:role/gha-routebox-shipments-api-dev
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push
        run: |
          docker build \
            --platform linux/amd64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            routebox-tracking-events/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Update image tag in deployment
        run: |
          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}|" \
            k8s/tracking-events/deployment.yaml

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name routebox-dev

      - name: Deploy
        run: kubectl apply -f k8s/tracking-events/
